
SET(MOZJS_SEARCH_PATHS
    /usr/local/
    /usr
    /opt
)

FIND_PATH(MOZJS_INCLUDE_DIR jsapi.h
    HINTS
    PATH_SUFFIXES include
    PATHS ${MOZJS_SEARCH_PATHS}
)
FIND_LIBRARY(MOZJS_LIBRARY mozjs-31
    HINTS
    PATH_SUFFIXES lib64 lib bin
    PATHS ${MOZJS_SEARCH_PATHS}
)

IF(MOZJS_INCLUDE_DIR AND MOZJS_LIBRARY)
   SET(MOZJS_FOUND TRUE)
ENDIF (MOZJS_INCLUDE_DIR AND MOZJS_LIBRARY)


IF(MOZJS_FOUND)
    MESSAGE(STATUS "Found mozjs: ${MOZJS_LIBRARY}")
ELSE(MOZJS_FOUND)
    MESSAGE(WARNING "Could not find mozjs")
ENDIF(MOZJS_FOUND)
